# SSH Forwards
# Format: [local_port]:[remote_host]:[remote_port] [user]@[host]
[ssh]
8443:192.168.49.2:8443 hunghlh@192.168.0.105
8080:localhost:8080 hunghlh@192.168.0.105

# Kubectl Forwards
# Format: [namespace] [resource] [local_port]:[remote_port]
[kubectl]
infras-postgres svc/postgres 5433:5432
infras-vault svc/vault 8200:8200
